# Generated by Django 2.0.1 on 2018-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberdetails',
            old_name='memberCity',
            new_name='memberCity1',
        ),
        migrations.RenameField(
            model_name='memberdetails',
            old_name='memberPincode',
            new_name='memberPincode1',
        ),
        migrations.RemoveField(
            model_name='memberdetails',
            name='memberAddress',
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='dateOfBirth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='fatherName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fathers Name'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='identificationMark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Identification Mark'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberAddress1',
            field=models.TextField(blank=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberAddress2',
            field=models.TextField(blank=True, verbose_name='Correspondence Address'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberCity2',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberHeight',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Height (in cms)'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberPincode2',
            field=models.IntegerField(max_length=9, null=True, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberProblems',
            field=models.CharField(blank=True, max_length=200, verbose_name='Physical Problem (if any)'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='memberWeight',
            field=models.IntegerField(max_length=3, null=True, verbose_name='Weight (in kgs)'),
        ),
    ]
