# Generated by Django 2.0.1 on 2018-01-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0002_auto_20180121_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetails',
            name='memberHeight',
            field=models.IntegerField(null=True, verbose_name='Height (in cms)'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberPincode1',
            field=models.IntegerField(blank=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberPincode2',
            field=models.IntegerField(null=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberWeight',
            field=models.IntegerField(null=True, verbose_name='Weight (in kgs)'),
        ),
    ]
