# Generated by Django 2.0.1 on 2018-01-21 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0003_auto_20180121_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='dueAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(0)], verbose_name='Due Amount'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberContactNumber',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
