# Generated by Django 2.0.1 on 2018-01-21 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0004_auto_20180121_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='paidAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(0)], verbose_name='Paid Amount'),
        ),
    ]
