# Generated by Django 2.0.1 on 2018-01-21 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0005_memberdetails_paidamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymdetails',
            name='gymContactNumber',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='gymdetails',
            name='gymNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gymdetails',
            name='gymPincode',
            field=models.IntegerField(verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='gymplans',
            name='planDuration',
            field=models.IntegerField(default=30, verbose_name='Duration (in days)'),
        ),
        migrations.AlterField(
            model_name='gymplans',
            name='planPrice',
            field=models.IntegerField(verbose_name='Price/Amount'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='dueAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Due Amount'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='memberEmergencyNumber',
            field=models.IntegerField(blank=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='paidAmount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)], verbose_name='Paid Amount'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staffContactNumber',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staffEmergencyNumber',
            field=models.IntegerField(blank=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staffNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='staffPincode',
            field=models.IntegerField(blank=True, verbose_name='Pincode'),
        ),
    ]
