# Generated by Django 2.0.1 on 2018-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegistration', '0006_auto_20180121_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetails',
            name='profileImage',
            field=models.ImageField(default='images/img.jpg', upload_to='images/'),
        ),
    ]
